# Before upgrading check that everything is available on all tier1 targets here:
# https://rust-lang.github.io/rustup-components-history
# [toolchain]
# channel = "nightly-2024-02-10"
# components = [ "rust-src", "rustfmt", "llvm-tools", "miri" ]
# targets = ["thumbv7em-none-eabi"]
[toolchain]
channel = "1.75"
components = ["rust-src", "rustfmt", "llvm-tools"]
targets = ["thumbv7em-none-eabi"]
